# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10
paginate_path: "page:num"
exclude: ["README.md", "vendor"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: johnpapa
title: JohnPapa.net
google_analytics: UA-18897867-1

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: JohnPapa.net

description: John Papa
author:
  name: John Papa
  github: johnpapa
  twitter: john_papa
  bio: Evangelist on the Loose
  email_md5: 0d3794fe37746ea54926ca6878712721

permalink: /:title

gems: ["jekyll-paginate"]

github_repo_url: https://github.com/johnpapa/johnpapa.github.io/

rss_path: feed.xml
rss_url: http://feeds.feedburner.com/johnpapa
categories_path: categories.html
#tags_path: tags.html

BASE_PATH:
